- hosts: localhost
 
  vars_files: 
    - test-single-replica-failure-vars.yml 
 
  tasks:
   - block:

       ###################################################
       #                PREPARE FOR TEST                 #
       # (Place artifacts in kubemaster, start logger &  # 
       # confirm OpenEBS operator is ready for requests. #
       ###################################################

       - name: Get $HOME of K8s master for kubernetes user
         shell: source ~/.profile; echo $HOME
         args: 
           executable: /bin/bash
         register: result_kube_home
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

       - name: Copy the percona spec and liveness script to kubemaster 
         copy:
           src: "{{ item }}"
           dest: "{{ result_kube_home.stdout }}"
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
         with_items: "{{ percona_files }}"

       - name: Replace volume-claim name with test parameters
         replace:
           path: "{{ result_kube_home.stdout }}/percona.yaml"
           regexp: '{{ item.0 }}'
           replace: '{{ item.1 }}'
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
         with_together:
           - "{{replace_item}}"
           - "{{replace_with}}

       - name: Copy the chaoskube specs to kubemaster  
         copy:
           src: "{{ item }}"
           dest: "{{ result_kube_home.stdout }}"
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
         with_items: "{{ chaoskube_files }}"

       - name: Start the log aggregator to capture test pod logs
         shell: >
           source ~/.profile;
           nohup stern "{{test_pod_regex}}" --since 1m > "{{result_kube_home.stdout}}/{{test_log_path}}" &
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

       - name: Check whether maya-apiserver pod is deployed
         shell: source ~/.profile; kubectl get pods | grep maya-apiserver
         args: 
           executable: /bin/bash
         register: result
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"    
         until: "'Running' in result.stdout"
         delay: 120 
         retries: 5
      
       ####################################################
       #          SETUP FAULT-INJECTION ENV               #
       # (Setup chaoskube deployment with an empty policy,#
       # deploy percona w/ a liveness check for DB writes)# 
       ####################################################

       - name: Setup the chaoskube infrastructure
         shell: source ~/.profile; kubectl apply -f {{ item }} 
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         with_items: "{{ chaoskube_files }}"

       - name: Confirm that the chaoskube deployment is running 
         shell: source ~/.profile; kubectl get pods --no-headers -l app=chaoskube
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result_chaoskube 
         until: "'chaoskube' and 'Running' in result_chaoskube.stdout"
         delay: 120
         retries: 15        

       - name: Create a configmap with the liveness sql script 
         shell: source ~/.profile; kubectl create configmap sqltest --from-file={{ percona_files.1 }} 
         args: 
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result 
         failed_when: "'configmap' and 'created' not in result.stdout"

       - name: Create percona deployment with OpenEBS storage
         shell: source ~/.profile; kubectl apply -f {{ percona_files.0 }}
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

       - name: Wait for 120s to ensure liveness check starts 
         wait_for:
           timeout: 120
         
       - name: Confirm percona pod is running
         shell: source ~/.profile; kubectl get pods --no-headers -l name=percona   
         args: 
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result
         until: "'percona' and 'Running' in result.stdout"
         delay: 120 
         retries: 15

       - name: Set chaoskube pod name to variable 
         set_fact: 
           chaospod: "{{ result_chaoskube.stdout_lines[0].split()[0] }}"

       - name: Get the name of the volume single replica deployment 
         shell: > 
           source ~/.profile; kubectl get deployments 
           -l openebs/replica=jiva-replica --no-headers
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result_deploy

       - name: Set the replica deployment name to variable 
         set_fact: 
           replica_deploy: "{{ result_deploy.stdout_lines[0].split()[0] }}"

       - name: Get the name of the single replica pod to a variable
         shell: >
           source ~/.profile; kubectl get pods 
           -l openebs/replica=jiva-replica --no-headers
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result_pod

       - name: Set the replica pod name to variable
         set_fact:
           replica_pod: "{{ result_pod.stdout_lines[0].split()[0] }}"

       - name: Get the name of the node the single replica pod is deployed
         shell: >
           source ~/.profile; kubectl describe pod {{ replica_pod }} | grep "Node:" | awk '{print $2}' | cut -d '/' -f1           
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result_node

       - name: Get the names of the nodes to be cordoned
         shell: >
           source ~/.profile; 
           kubectl get nodes --no-headers | grep -v {{ result_node.stdout }} | awk '{print $1}'           
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result_nodes

       - name: Cordon the nodes
         shell: >
           source ~/.profile; kubectl cordon {{ item }}           
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         with_items: "{{ result_nodes.stdout_lines }}"                                      

       ########################################################
       #        INJECT FAULTS FOR SPECIFIED PERIOD            #
       # (Obtain begin marker before fault-inject(FI),do ctrl # 
       # failures, verify successful FI via end marker)       # 
       ########################################################

       - name: Get the resourceVersion of the replica deployment
         shell: >
           source ~/.profile; kubectl get deploy 
           {{ replica_deploy }} -o yaml | grep resourceVersion
           | awk '{print $2}' | sed 's|"||g'
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: rv_bef          
 
       - name: Initiate periodic replica failures from chaoskube
         shell: >
           source ~/.profile; kubectl exec {{ chaospod }}  
           -- timeout -t {{ chaos_duration }} chaoskube 
           --labels 'openebs/replica=jiva-replica'
           --no-dry-run --interval={{ chaos_interval }}s 
           --debug
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: chaos_result
         ignore_errors: true 

       - name: Get the resourceVersion of the replica deployment
         shell: >
           source ~/.profile; kubectl get deploy 
           {{ replica_deploy }} -o yaml | grep resourceVersion
           | awk '{print $2}' | sed 's|"||g'
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: rv_aft    
 
       - name: Compare resourceVersions of replica deployments 
         debug: 
           msg: "Verified replica pods were restarted by chaoskube"
         failed_when: "rv_bef.stdout | int == rv_aft.stdout | int"

       ########################################################
       #        VERIFY RESILINCY/FAULT-TOLERATION             #
       # (Confirm liveness checks on percona are successful & #
       # pod is still in running state)                       #
       ########################################################

       - name: Confirm percona application is still running
         shell: source ~/.profile; kubectl get pods --no-headers -l name=percona   
         args: 
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result
         until: "'percona' and 'Running' in result.stdout"
         delay: 120 
         retries: 15

       ########################################################
       #                        CLEANUP                       #			      
       # (Tear down application, liveness configmap as well as#
       # the FI (chaoskube) infrastructure. Also stop logger) # 
       ########################################################
       - name: Uncordon the nodes
         shell: >
           source ~/.profile; kubectl uncordon {{ item }}           
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         with_items: "{{ result_nodes.stdout_lines }}"


       - name: Terminate the log aggregator
         shell: source ~/.profile; killall stern
         args:
           executable: /bin/bash 
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"  

       - set_fact:
           flag: "Pass"

     rescue: 
       - set_fact: 
           flag: "Fail"

     always:
       - include: test-single-replica-failure-cleanup.yml
         when: clean | bool

       - name: Send slack notification
         slack: 
           token: "{{ lookup('env','SLACK_TOKEN') }}"
           msg: '{{ ansible_date_time.time }} TEST: {{test_name}}, RESULT: {{ flag }}'
         when: slack_notify | bool and lookup('env','SLACK_TOKEN')

