---
apiVersion: v1
kind: Pod
metadata:
  name: tests-fio
  labels:
    name: tests-fio
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: tests-fio
    image: openebs/tests-fio
    volumeMounts:
    - mountPath: /datadir1
      name: demo-vsm1-vol1
  volumes:
  - name: demo-vsm1-vol1
    flexVolume:
      driver: "openebs/openebs-iscsi"
      options:
        name: "demo-vsm1-vol1"
        openebsApiUrl: "http://172.28.128.4:5656/latest"
        size: "2G"
