---
- name: Establish ISCSI Connection
  open_iscsi:
    show_nodes: yes
    portal: "{{hostvars[groups['openebs-mayamasters'][0]]['openebs_target_portal']}}"
    discover: yes
    login: yes
  register: result
  until: "'iqn' in result.nodes[0]"
  retries: 6
  delay: 10
  become: true

- name: Identify Block Device
  shell: "iscsiadm -m session -P 3 | grep 'Attached scsi disk' | awk '{print $4}'"
  register: device
  become: true

- name: Create a File System
  filesystem:
    fstype: ext4
    dev: /dev/{{device.stdout}}
    force: no
  become: true

- name: Mount Device by Label
  mount:
    name: /mnt/iscsi
    src: /dev/{{device.stdout}}
    fstype: ext4
    opts: discard,_netdev
    state: mounted
  become: true

- name: fio docker image pull
  docker_image:
    name: "{{openebs_image}}"
    state: present
    pull: true
    timeout: 120
  become: true

- name: fio docker instantiate
  docker_container:
    name: fio-runner
    image: "{{openebs_image}}"
    command: /fio_runner.sh Basic "{{fio_run_duration}}" 
    volumes:
      - /mnt/iscsi:/datadir1
    state: started
  become: true
