---
test_name: test-node-eviction-out-of-disk

namespace: nodeeviction

percona_links:
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/percona.yaml
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/sql-test.sh

percona_files:
  - percona.yaml
  - sql-test.sh

replace_item:
  - demo-vol1-claim
  - demo-vol1

replace_with:
  - test-node-eviction
  - test-nodeeviction

test_pod_regex: maya*|openebs*|pvc*|percona*

test_log_path: setup/logs/test-node-eviction-out-of-disk.log

key: node.kubernetes.io/out-of-disk

