---
# Do not change the order of the scripts.
# They have to be run in the order defined below.

configure_scripts:
  - configure_k8s_master.sh
  - configure_k8s_weave.sh

weave_depends:
  - weave_images_{{ k8s_version }}.tar
  - weave-daemonset-k8s-1.6.yaml

k8s_images: k8s_images_{{ k8s_version }}.tar

weave_images_path: "{{ ansible_env.HOME}}/setup/weave"

k8s_images_path: "{{ ansible_env.HOME}}/setup/kubernetes"

# Do not change the order of the packages
# They have to be installed in the order defined below.

k8s_dpkg_packages:
  - kubelet.deb
  - kubernetes-cni.deb
  - kubectl.deb
  - kubeadm.deb

