kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-cpvr1-claim
spec:
  storageClassName: openebs-cstor-r1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench-cpvr1
spec:
  template:
    spec:
      containers:
      - name: dbench-cpvr1
        image: logdna/dbench:latest
        imagePullPolicy: Always
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          # - name: DBENCH_QUICK
          #   value: "yes"
          - name: FIO_SIZE
            value: 1G
          - name: FIO_OFFSET_INCREMENT
            value: 256M
          # - name: FIO_DIRECT
          #   value: "0"
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: dbench-cpvr1-claim
  backoffLimit: 4
