---
test_name: verify_replica_deployment_with_node_affinity

patch_file: replica_patch.yml

create_sc: storage-class.yaml

percona_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/percona/demo-percona-mysql-pvc.yaml

replica_count: 2

namespace: node-affinity

utils_path: /home/giri/new_fork/openebs/e2e/ansible/playbooks/utils

test_pod_regex: maya*|openebs*|pvc*|percona*|

test_log_path: setup/logs/node_affinity_test.log
