---
# Steps
# 1) Downloading helm
# 2) Initialising helm
# 3) Check if the tiller is deployed
# 4) Create service account for tiller
# 5) Create cluster role binding
# 6) Update the deployment with the service account
# 7) Install OpenEBS using stable helm chart
# 8) Check if the installation is successful
# 9) Create the default storage classes

- name: 1) Install helm
  shell: curl -Lo /tmp/helm-linux-amd64.tar.gz https://kubernetes-helm.storage.googleapis.com/helm-v2.6.2-linux-amd64.tar.gz; tar -xvf /tmp/helm-linux-amd64.tar.gz -C /tmp/; chmod +x  /tmp/linux-amd64/helm && sudo mv /tmp/linux-amd64/helm /usr/local/bin/
  args:
    executable: /bin/bash

- name: 2) Tiller setup
  shell: helm init
  args:
    executable: /bin/bash
  register: tiller_out
  until: "'Happy Helming' in tiller_out.stdout"
  delay: 30
  retries: 15

- name: 3) Check if tiller is configured
  shell: helm version
  args:
    executable: /bin/bash
  register: tiller_version
  until: "'Server: &version.Version' in tiller_version.stdout"
  delay: 120
  retries: 10

- name: 4) Creating service account
  shell: kubectl -n kube-system create sa tiller
  args:
    executable: /bin/bash
  register: tiller
  until: "'serviceaccount \"tiller\" created' in tiller.stdout"
  delay: 60
  retries: 5

- name: 5) Create cluster rolebinding
  shell: kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
  args:
    executable: /bin/bash
  register: crb
  until: "'clusterrolebinding \"tiller\" created' in crb.stdout"
  delay: 20
  retries: 5

- name: 6) Getting home directory in kubernetes master
  shell: source ~/.profile; echo $HOME
  args:
    executable: /bin/bash
  register: result_kube_home

- name: 6a) Copying the patch yaml file to kubernetes master
  copy:
    src: "{{ update_deploy_file }}"
    dest: "{{ result_kube_home.stdout }}"

- name : 6b) Update the deployment
  shell: kubectl -n kube-system patch deploy/tiller-deploy -p "$(cat {{ update_deploy_file }})"
  args:
    executable: /bin/bash
  register: tiller_deploy
  until: "'deployment \"tiller-deploy\" patched' in tiller_deploy.stdout"
  delay: 20
  retries: 6

#- name: Adding OpenEBS charts to repo
#  shell: helm repo add openebs-charts "{{ charts }}"
#  args:
#    executable: /bin/bash
#  register: repos
#  until: "'\"openebs-charts\" has been added to your repositories' in repos.stdout"
#  delay: 20
#  retries: 6

#- name: Update the repo
#  shell: helm repo update
#  args:
#    executable: /bin/bash
#  register: update
#  until: "'Update Complete' in update.stdout"
#  delay: 20
#  retries: 6

- name: 7) Install openebs
  shell: helm install stable/openebs --name openebs --namespace openebs
  args:
    executable: /bin/bash
  register: openebs_out
  until: "'The OpenEBS has been installed' in openebs_out.stdout"
  delay: 120
  retries: 5

- name: 8) Check if provisioner is deployed
  shell: kubectl get pods -n "{{ namespace }}" | grep "openebs-provisioner"
  args:
    executable: /bin/bash
  register: deployment
  until: "'Running' in deployment.stdout"
  delay: 60
  retries: 15

- name: 8a) Check if maya-apiserver is deployed
  shell: kubectl get pods -n "{{ namespace }}" | grep "openebs-apiserver"
  args:
    executable: /bin/bash
  register: api_server
  until: "'Running' in api_server.stdout"
  delay: 60
  retries: 15

- name: 9) Create the default storage classes
  shell: kubectl apply -f "{{ storage_classes }}"
  args:
    executable: /bin/bash


