---
- name: Establish ISCSI Connection
  open_iscsi:
    show_nodes: yes
    portal: "{{hostvars[groups['openebs-mayamaster'][0]]['openebs_target_portal']}}"
    discover: yes
    login: yes
  register: result
  until: "'iqn' in result.nodes[0]"
  retries: 6
  delay: 10
  become: true

- name: Identify Block Device
  shell: "iscsiadm -m session -P 3 | grep 'Attached scsi disk' | awk '{print $4}'"
  register: device
  become: true

- name: IOmeter docker image build
  docker_image:
    name: "{{iometer_image}}"
    state: present
    path: "{{dockerfile_path}}"
    rm: true
    timeout: 600
  become: true

- name: Get localhost's public IP address
  connection: local
  shell: echo "{{ansible_default_ipv4.address}}"
  register: local_address      

- name: IOmeter docker instantiate
  docker_container:
    name: iometer-runner
    image: "{{iometer_image}}"
    devices:
    - '/dev/{{device.stdout}}:/dev/sdb'
    network_mode: host
    command: /dynamo -i "{{iometer_host}}" -m "{{local_address.stdout}}" 
    state: started
  become: true
