---
test_name: hyperconverged_percona_db_on_k8s

test_log_path: setup/logs/hyperconverged_percona_db_on_k8s.log

test_pod_regex: maya*|openebs*|pvc*|percona*

percona_mysql_plugin_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/percona/demo-percona-mysql-pvc.yaml

pod_yaml_alias: demo-percona-mysql-pvc.yaml

percona_mysql_vol_size: 5G

replace_item:
  - demo-vol1-claim
  - demo-vol1

replace_with:
  - percona-db-claim
  - percona-db

files:
  - Dockerfile
  - MySQLLoadGenerate.sh

get_pip: get-pip.py

pip_packages:
  - 'docker-py==1.9.0'

mysql_load_duration: 120

namespace: percona-mysql-test

test_suite_id: 826

test_case_id: 166350
