---
- name: Get pvc name to verify successful pvc deletion
  shell: source ~/.profile; kubectl get pvc {{ replace_with.0 }} -n {{ namespace }} -o custom-columns=:spec.volumeName --no-headers
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: pvc
  changed_when: true

- name: Wait {{ mysql_load_duration }} sec for I/O completion
  wait_for:
    timeout: "{{ mysql_load_duration }}"

- name: Delete percona mysql pod
  include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy.yml"
  vars:
    ns: "{{ namespace }}"
    app_yml: "{{ pod_yaml_alias }}"

- include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy_check.yml"
  vars:
    ns: "{{ namespace }}"
    app: percona

- name: Confirm pvc pod has been deleted
  shell: source ~/.profile; kubectl get pods | grep {{ pvc.stdout }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'pvc' and 'Running' not in result.stdout"
  delay: 30
  retries: 10
  changed_when: true

- name: Delete namespace
  shell: source ~/.profile; kubectl delete ns {{ namespace }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

