---
- include: pre-requisites.yml

- include: setup-disks.yml
  when: cluster_type == "managed"

- include: setup-kubernetes.yml

- include: setup-stern.yml

- include: setup-openebs.yml

- include: run-tests.yml 
