---
- name: Delete the openebs storage classes
  shell: source ~/.profile; kubectl delete -f {{ ansible_env.HOME }}/{{ openebs_storageclasses_alias }}
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Get the list of openebs storage classes deployed from other YAMLs
  shell: source ~/.profile; kubectl get sc | grep openebs.io/provisioner-iscsi | cut -d ' ' -f1
  args:
    executable: /bin/bash
  register: list_sc

- name: Delete storage classes deployed from other YAMLs
  shell: source ~/.profile; kubectl delete sc {{ item }}
  args:
    executable: /bin/bash
  with_items: "{{ list_sc.stdout_lines }}"

- name: Confirm storage classes have been deleted
  shell: source ~/.profile; kubectl get sc
  args:
    executable: /bin/bash
  register: result
  until: "'openebs.io/provisioner-iscsi' not in result.stdout"
  delay: 10
  retries: 6

- name: Delete the openebs pre-release features
  shell: source ~/.profile; kubectl delete -f {{ ansible_env.HOME }}/{{ openebs_pre_release_alias }}
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Confirm pre-release features have been deleted
  shell: source ~/.profile; kubectl get cast -n openebs
  args:
    executable: /bin/bash
  register: result
  until: "'No resources found.' in result.stderr"
  delay: 20
  retries: 10

- name: Delete the openebs operator
  shell: source ~/.profile; kubectl delete -f {{ ansible_env.HOME }}/{{ openebs_operator_alias }}
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Confirm pod has been deleted
  shell: source ~/.profile; kubectl get pods -n openebs
  args:
    executable: /bin/bash
  register: result
  until: "'maya-apiserver' and 'openebs-provisioner' and 'openebs-snapshot-operator' not in result.stdout"
  delay: 30
  retries: 10

- name: Delete the artifacts
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
  loop:
    - "{{ openebs_storageclasses_alias }}"
    - "{{ openebs_operator_alias }}"
    - "{{ openebs_pre_release_alias }}"