---
test_name: test-volume-capacity

test_log_path: setup/logs/volume_capacity.log

test_pod_regex: maya*|openebs*|pvc*|vol*|fio*

namespace: volume

fio: demo-fio-openebs.yml

fio_files:
  - demo-fio-openebs.yml

mount_point: /datadir
