---

#########################################
# Kubernetes Deployment Specification   #
#########################################

#Kubernetes Version to be used for deployment
#Accepted Entries (Valid Kubernetes Version): default:1.6.3
#Accepted Entries (Valid Weave Version): default:1.9.4

k8s_version: 1.6.3
weave_version: 1.9.4

#list of kubernetes versions released.
#do not tamper the list unless you know
#what you are doing...

k8s_version_list:
  - 1.6.2
  - 1.6.3
  - 1.6.4
  - 1.6.5
  - 1.6.6
  - 1.7.0
  - 1.7.2
  - 1.7.4
  - 1.7.5

weave_version_list:
  - 1.9.4
  - 2.0.4 

#########################################
# OpenEBS Deployment Specifications     #
#########################################

#User-defined size for the volume that openebs creates
#Accepted Entries(Valid Volume Sizes): default:5G

openebs_vol_size: 5G

#Available CIDR for allocating IP Addresses for containers
#Accepted Entries (Valid CIDR): default:172.28.128.1/24

cn_network_cidr: 20.10.49.110/25

#Network interface for CIDR
#Accepted Entries (Valid Network Interface): default:enp0s8

cn_interface: ens160

#Mode of openEBS deployment 
#Accepted Entries (dedicated, hyperconverged): default:dedicated 

deployment_mode: hyperconverged 

#Option specifically for vagrant VMs
#Accepted Entries(true, false): default:false

is_vagrant_vm: true

#########################################
# Ansible Runtime Specifications        #
#########################################

#Option to run the sample demo of OpenEBS
#Accepted Entries(true, false): default:true

run_demo: true

#Option to setup Ansible Runtime Analysis playbook recorder
#Accepted Entries(true, false): default:true

ara_setup: true 

#Option to enable slack notifications to specified channel
#Accepted Entries(true, false): default:true

slack_notify: true

#########################################
# OpenEBS Test Specifications           #
#########################################

#Option to run cleanup functions in tests
#Accepted Entries(true, false): default:true

clean: true

#########################################
# OpenEBS CI Specifications             #
#########################################

#Option to select type of CI build
#Accepted Entries(quick, normal): default:normal
#quick build uses preconfigured VMs, 
#normal builds upon vanilla VMs

build_type: normal


