---
openebs_operator_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/openebs-operator.yaml

openebs_operator_alias: openebs-operator.yaml 

openebs_storageclasses_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/openebs-storageclasses.yaml

openebs_storageclasses_alias: openebs-storageclasses.yaml

# Image tag for openebs containers
# Accepted entries (ci, latest): Default: latest
test_tag: ci

namespace: openebs
