---
- name: Delete the iSCSI target
  shell: source ~/.profile; kubectl delete -f {{ volume_def }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Confirm that the storage volume is deleted
  shell: source ~/.profile; kubectl get pvc
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'pvc' not in result.stdout"
  delay: 120
  retries: 6

- name: Confirm percona pod is deleted
  shell: >
    source ~/.profile;
    kubectl get pods -l name=percona --no-headers
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'percona' not in result.stdout"
  delay: 120
  retries: 6

- name: Get pvc name to verify successful pvc deletion
  shell: source ~/.profile; kubectl get pvc | grep {{ replace_with.0 }} | awk {'print $3'}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: pvc

- name: Confirm pvc pod has been deleted
  shell: source ~/.profile; kubectl get pods | grep {{ pvc.stdout }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  failed_when: "'pvc' and 'Running' in result.stdout"
  delay: 30
  retries: 10

