# Define a storage classes supported by OpenEBS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-basic
provisioner: openebs.io/provisioner-iscsi
parameters:
  pool: hostdir-var
  replica: "2"
  size: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-percona
provisioner: openebs.io/provisioner-iscsi
parameters:
  pool: hostdir-var
  replica: "2"
  size: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-jupyter
provisioner: openebs.io/provisioner-iscsi
parameters:
  pool: hostdir-var
  replica: "2"
  size: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-mongodb
provisioner: openebs.io/provisioner-iscsi
parameters:
  pool: hostdir-var
  replica: "2"
  size: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-cassandra
provisioner: openebs.io/provisioner-iscsi
parameters:
  pool: hostdir-var
  replica: "2"
  size: 5G

