apiVersion: v1
kind: Pod
metadata:
  name: busybox-cstor-ns
  namespace: default
spec:
  containers:
  - command:
       - sh
       - -c
       - 'date > /mnt/store1/date.txt; hostname >> /mnt/store1/hostname.txt; sync; sleep 5; sync; tail -f /dev/null;'
    image: busybox
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
    - mountPath: /mnt/store1
      name: demo-vol1
  volumes:
  - name: demo-vol1
    persistentVolumeClaim:
      claimName: openebs-pvc-in-custom-ns
---
