apiVersion: v1
kind: Pod
metadata:
  name: busybox-clone-cstor-ns
  namespace: default
spec:
  containers:
  - command:
       - sh
       - -c
       - 'tail -f /dev/null'
    image: busybox
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
    - mountPath: /mnt/store2
      name: demo-snap-vol
  volumes:
  - name: demo-snap-vol
    persistentVolumeClaim:
      claimName: demo-snap-vol-claim-cstor-ns
