# k8s-jupyter-pod.yml
# Description: Deploy Jupyter application using OpenEBS volume.

###############################################################################################
#Test Steps:
#1. Check whether the OpenEBS components are deployed.
#2. Download the test artifacts to k8s master.
#3. Deploy Jupyter application.
#4. Check if the application pod is up and running
#5. Check if the Jupyter service us up.
#6. Perform cleanup of test artifacts.
###############################################################################################

- hosts: localhost

  vars_files:
    - k8s-jupyter-pod-vars.yml

  tasks:

   - block:

       - include: k8s-jupyter-pod-prereq.yml

       - name: a) Download YAML for jupyter notebook server plugin
         include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/get_url.yml"
         vars:
           url: "{{ jupyter_plugin_link }}"
           dest: "{{ result_kube_home.stdout }}/{{ pod_yaml_alias }}"

       - name: 2b) Check whether maya-apiserver is deployed
         include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/deploy_check.yml"
         vars:
            ns: "{{ operator_ns }}"
            app: maya-api

       - name: 2c) Replace volume size in plugin YAML
         lineinfile:
           path: "{{ result_kube_home.stdout }}/{{ pod_yaml_alias }}"
           regexp: "storage:"
           line: "      storage: \"{{jupyter_server_vol_size}}\""
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

       - name: 3) Deploy jupyter notebook server pod
         include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/deploy_task.yml"
         vars:
           app_yml: "{{ pod_yaml_alias }}"
           ns: default

       - name: 4) Confirm pod status is running
         include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/deploy_check.yml"
         vars:
            ns: default
            app: jupyter

       - name: 5) Verify that the jupyter notebook server is a cluster service
         shell: source ~/.profile; kubectl get svc
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result_service
         failed_when: "'jupyter-service' not in result_service.stdout"

       - name: Test Passed
         set_fact:
           flag: "Test Passed"
           status_id: 1

       - name: Set Status
         set_fact:
           status: "good"

     rescue:
       - name: Test Failed
         set_fact:
           flag: "Test Failed"
           status_id: 5

       - name: Set Status
         set_fact:
           status: "danger"

     always:
       - block:

           - include: k8s-jupyter-pod-cleanup.yml

           - name: Test Cleanup Passed
             set_fact:
               cflag: "Cleanup Passed"

         rescue:
           - name: Test Cleanup Failed
             set_fact:
               cflag: "Cleanup Failed"

         always:

           - include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/stern_task.yml"
             vars:
               status: stop

           - block:
               - name: Update Testrail
                 shell: source ~/.profile; python3 {{ inventory_dir | dirname }}/files/updater.py -tuser {{ testrail_user }} -tpass {{ testrail_password }} -sid {{ test_suite_id }} -cid {{ test_case_id }} -stid {{ status_id }}
                 args:
                   executable: /bin/bash

               - name: Testrail Updated
                 set_fact:
                   tflag: "Testrail Updated"

             rescue:
               - name: Testrail Update failed
                 set_fact:
                   tflag: "Testrail Update Failed"

           - name: Send slack notification
             slack:
               token: "{{ lookup('env','SLACK_TOKEN') }}"
               msg: '{{ ansible_date_time.time }} TEST: {{test_name}}, RESULT: {{ flag }},{{ cflag }},{{tflag}}'
               color: "{{status}}"
             when: slack_notify | bool and lookup('env','SLACK_TOKEN')

