---
- name: Get pvc name to verify successful pvc deletion
  shell: source ~/.profile; kubectl get pvc -n | grep {{ volume_claim }} | awk {'print $3'}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: pvc
  changed_when: true

- name: Delete jupyter server pod
  include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy.yml"
  vars:
    ns: default
    app_yml: "{{ pod_yaml_alias }}"

- name: Confirm jupyter pod has been deleted
  include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy_check.yml"
  vars:
    ns: default
    app: jupyter

- name: Confirm pvc pod has been deleted
  shell: source ~/.profile; kubectl get pods -n | grep {{ pvc.stdout }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'pvc' and 'Running' not in result.stdout"
  delay: 30
  retries: 10
  changed_when: true

