---
- include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy.yml"
  vars:
    app_yml: "{{volume_def }}"
    ns: "{{ namespace }}"

- name: Confirm that the storage volume is deleted
  shell: source ~/.profile; kubectl get pvc -n {{namespace}}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'pvc' not in result.stdout"
  delay: 120
  retries: 6
  changed_when: true

- name: Delete namespace
  shell: source ~/.profile; kubectl delete ns {{namespace}}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
