---

       - name: Check the node is brought up
         shell: source ~/.profile; kubectl get nodes | grep {{node1.stdout}} | awk '{print $2}'
         args:
           executable: /bin/bash
         register: result1
         until: "'NotReady' not in result1.stdout"
         delay: 30
         retries: 6
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         changed_when: True
         ignore_errors: True

       - block:

           - name: Bring up node if it is down
             include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/vagrant-halt-up-task.yml"
             vars:
               vagrant_op: up
               nodename: "{{node1.stdout}}"

           - name: Check the node is brought up
             shell: source ~/.profile; kubectl get nodes | grep {{node1.stdout}} | awk '{print $2}'
             args:
               executable: /bin/bash
             register: result
             until: "'NotReady' not in result.stdout"
             delay: 30
             retries: 6
             delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
             changed_when: True

           - name: sleep for 120s
             wait_for:
               timeout: "120"

         when: "'NotReady' in result1.stdout"


       - name: Get pvc name to verify successful pvc deletion
         shell: source ~/.profile; kubectl get pvc -n {{ namespace }} | grep {{ replace_with.0 }} | awk {'print $3'}
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: pvc
         changed_when: true

       - include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy.yml"
         vars:
           ns: "{{ namespace }}"
           app_yml: "{{ percona_files.0 }}"

       - include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy_check.yml"
         vars:
           ns: "{{ namespace }}"
           app: percona

       - name: Confirm pvc pod has been deleted
         shell: source ~/.profile; kubectl get pods -n {{ namespace }} | grep {{ pvc.stdout }}
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result
         failed_when: "'pvc' and 'Running' in result.stdout"
         delay: 30
         retries: 10
         changed_when: true

       - name: Remove the percona liveness check config map
         shell: source ~/.profile; kubectl delete cm sqltest -n {{ namespace }}
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result
         failed_when: "'configmap' and 'deleted' not in result.stdout"
         changed_when: true

       - name: Delete namespace
         command: kubectl delete ns {{ namespace }}
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         changed_when: true

       - name: Remove test artifacts
         file:
           path: "{{ result_kube_home.stdout }}/{{ item }}"
           state: absent
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         with_items:
           - "{{percona_files}}"

       - name: sleep for 50 seconds and continue with play
         wait_for:
           timeout: "50"
