apiVersion: v1
version: 0.0.1
name: openebs
appVersion: 0.4.0
description: Containerized Storage for Containers
icon: https://github.com/openebs/chitrakala/blob/master/logo/png/logo-01.png
home: http://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - iSCSI
  - storage
sources:
  - https://github.com/openebs/openebs
