# Default values for OpenEBS

## If true, create & use RBAC resources
##
rbacEnable: true

rbac:
  namespace: "openebs"

operator:
  name: "openebs-maya-operator"

image:
  pullPolicy: IfNotPresent

apiserver:
  image: "openebs/m-apiserver"
  tag: "0.5.2"

provisioner:
  image: "openebs/openebs-k8s-provisioner"
  tag: "0.5.2"
  mayaportalurl: "https://mayaonline.io/"
  monitorurl: "http://127.0.0.1:32515/dashboard/db/openebs-volume-stats?orgId=1"
  monitorvolkey: "&var-OpenEBS"

jiva:
  image: "openebs/jiva:0.5.1"
  replicas: 3

policies:
  monitoring:
    enabled: true
    image: "openebs/m-exporter:0.5.1"
