---
test_name: dedicated_mysql_db_on_k8s

mysql_plugin_link: https://raw.githubusercontent.com/openebs/openebs/8e33dac25b2c86f9228a98335b07f45585e51485/k8s/demo/specs/demo-mysql-openebs-plugin.yaml

pod_yaml_alias: demo-mysql-openebs-plugin.yaml

mysql_vol_size: 5G

files:
  - Dockerfile
  - MySQLLoadGenerate.sh

deb_packages:
  - python-pip

pip_packages:
  - 'docker-py==1.9.0'

mysql_load_duration: 120

