apiVersion: v1
kind: Service
metadata:
  name: redis-standalone
  labels:
    app: redis-standalone
spec:
  clusterIP: None
  ports:
    - port: 6379
  selector:
    app: redis-standalone
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-standalone
spec:
  serviceName: redis-standalone
  replicas: 1
  selector:
    matchLabels:
      app: redis-standalone
  template:
    metadata:
      name: redis-standalone
      labels:
        app: redis-standalone
    spec:
      containers:
      - name: redis
        image: redis:latest
        args: [ "--appendonly", "yes" ]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      annotations:
        volume.beta.kubernetes.io/storage-class: openebs-standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5G
