apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-test
  annotations:
    cas.openebs.io/create-volume-template: jiva-volume-create-default-0.7.0
    cas.openebs.io/delete-volume-template: jiva-volume-delete-default-0.7.0
    cas.openebs.io/read-volume-template: jiva-volume-read-default-0.7.0  
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "3"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G

