---
test_name: libiscsi_test_suite

test_log_path: setup/logs/libiscsi_test_suite.log

test_pod_regex: maya*|openebs*|pvc*

volume_def: test-pvc.yaml

test_list: run-tests.out

deb_packages:
  - libiscsi-bin

namespace: libiscsi-test

utils_path: openebs/e2e/ansible/playbooks/utils

test_suite_id: 826

test_case_id: 166353
