---
- name: Update apt cache
  command: apt-get update
  become: true
  ignore_errors: true
  delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
  tags:
  - skip_ansible_lint

- name: Install mysql-client on K8S-master
  shell: apt-get install -y {{ item }}
  become: true
  with_items: "{{ deb_packages }}"
  delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
  tags:
   - skip_ansible_lint

- name: Get $HOME of K8s master for kubernetes user
  shell: source ~/.profile; echo $HOME
  args:
    executable: /bin/bash
  register: result_kube_home
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/stern_task.yml"
  vars:
    status: start

