---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: percona-jd
  labels:
    name: percona-jd
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: percona-jd 
  template: 
    metadata:
      labels: 
        name: percona-jd
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: percona
          image: percona
          args:
            - "--ignore-db-dir"
            - "lost+found"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: k8sDem0
          ports:
            - containerPort: 3306
              name: percona-jd
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: demo-vol1
      volumes:
        - name: demo-vol1
          persistentVolumeClaim:
            claimName: percona-jd-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: percona-jd-claim
spec:
  storageClassName: openebs-jiva-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: v1
kind: Service
metadata:
  name: percona-mysql-jd
  labels:
    name: percona-mysql-jd
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      name: percona-jd

