---
test_name: Scaleup_cassandra-application-pods

openebs_operator_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/openebs-operator.yaml

cassandra_service_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/cassandra/cassandra-service.yaml

svc_yaml_alias: cassandra-service.yaml

cassandra_stateful_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/cassandra/cassandra-statefulset.yaml

stateful_yaml_alias: cassandra-statefulset.yaml

cassandra_loadgen_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/cassandra/cassandra-loadgen.yaml

loadgen_yaml_alias: cassandra-loadgen.yaml

io_minutes: 3

namespace: scaleup-pods

profile: ~/.profile

cassandra_artifacts:
  -  cassandra-service.yaml
  -  cassandra-statefulset.yaml

test_log_path: setup/logs/scaleup-cassandra-pods.log

test_pod_regex: maya*|openebs*|pvc*|cassandra*

test_artifacts:
  -  cassandra-service.yaml
  -  cassandra-statefulset.yaml
  -  cassandra-loadgen.yaml

test_suite_id: 826

test_case_id: 166364
