---

volume_policy: vol-policies.yaml

openebs_ns_operator: openebs-operator-ns-openebs.yaml

test_name: Testing Volume taint policy

test-pvc: https://raw.githubusercontent.com/openebs/openebs/master/e2e/ansible/playbooks/hyperconverged/test-k8s-storage-pool/test-pvc.yaml 

operator_key: key1

operator_value: value1

pvc_key: key2

pvc_value: value2

namespace: percona

node1: kubeminion-01

operator_list:
       - 'key: "k"'
       - 'value: "v"'
replaceoperator_list: 
              - 'key: "key1"'
              - 'value: "value1"'
list:
   - "key: jk"
   - "value: jv"

replace_list:
   - "key: key2"
   - "value: vaule2"

node_names:
  - kubeminion-02
  - kubeminion-03

openebs_operator_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/openebs-operator.yaml
