apiVersion: v1
kind: Service
metadata:
  name: maya-apiserver-service
{{- if .Values.rbacEnable }}
  namespace: {{ .Values.rbac.namespace }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - name: api
    port: 5656
    protocol: TCP
    targetPort: 5656
  selector:
    name: maya-apiserver
  sessionAffinity: None
