---
- name: Delete percona mysql pod 
  shell: source ~/.profile; kubectl delete -f {{ percona_files.0 }} 
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Confirm percona pod has been deleted
  shell: source ~/.profile; kubectl get pods -l name=percona 
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'percona' not in result.stdout"
  delay: 30 
  retries: 10

- name: Get pvc name to verify successful pvc deletion
  shell: source ~/.profile; kubectl get pvc | grep {{ replace_with.0 }} | awk {'print $3'}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: pvc

- name: Confirm pvc pod has been deleted
  shell: source ~/.profile; kubectl get pods | grep {{ pvc.stdout }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  failed_when: "'pvc' and 'Running' in result.stdout"
  delay: 30
  retries: 10

- name: Remove the percona liveness check config map 
  shell: source ~/.profile; kubectl delete cm sqltest 
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  failed_when: "'configmap' and 'deleted' not in result.stdout"

- name: Delete the chaoskube infrastructure
  shell: source ~/.profile; kubectl delete -f {{ item }}
  args: 
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  with_items: "{{ chaoskube_files }}"

- name: Confirm that the chaoskube pod has been deleted
  shell: source ~/.profile; kubectl get pods -l app=chaoskube
  args: 
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'chaoskube' not in result.stdout"

- name: Confirm the chaoskube sa has been deleted
  shell: >
    source ~/.profile; 
    kubectl get sa --no-headers -o custom-columns=:metadata.name
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  failed_when: "'chaoskube' in result.stdout"

- name: Confirm the chaoskube clusterrolebinding has been deleted
  shell: >
    source ~/.profile;
    kubectl get clusterrolebinding --no-headers -o custom-columns=:metadata.name
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  failed_when: "'chaoskube' in result.stdout"

- name: Remove test artifacts
  shell: rm -rf {{ item.0 }}; rm -rf {{ item.1 }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  with_together:
    - "{{percona_files}}"
    - "{{chaoskube_files}}"
  
 
 
