---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: blockdeviceclaims.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: blockdeviceclaims
    # singular name to be used as an alias on the CLI and for display
    singular: blockdeviceclaim
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: BlockDeviceClaim
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - bdc
  additionalPrinterColumns:
  - JSONPath: .spec.blockDeviceName
    name: BlockDeviceName
    description: Identifies the block device associated with the claim
    type: string
  - JSONPath: .status.phase
    name: Phase
    description: Identifies the phase of block device claim
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
---
